version: "3.7"
services:
  next:
    container_name: next
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    environment:
      PORT: 80
      NODE_ENV: "development"
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - 80:80
